#!/usr/bin/env bash
# Per-round phase breakdown for Borůvka-OMP at n=10^5, 1 thread vs 10 threads.
# Reuses graphs already generated by run_experiments.sh (in /tmp/exp_graphs/).

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

PROF="$ROOT/build/tools/profile_omp"
GEN="$ROOT/build/tools/gen_graph"
[ -x "$PROF" ] || { echo "missing $PROF; build first"; exit 1; }

GRAPH_DIR=/tmp/exp_graphs
OUT="$ROOT/results/e5_profile.csv"
mkdir -p "$ROOT/results" "$GRAPH_DIR"

N=100000
SEEDS=(42 43 44 45 46)
C=4
p_for() { awk -v n=$1 -v c=$C 'BEGIN{printf "%.10f", c*log(n)/n}'; }

for s in "${SEEDS[@]}"; do
    g="$GRAPH_DIR/g_${N}_s${s}.txt"
    if [ ! -f "$g" ]; then
        "$GEN" "$N" "$(p_for $N)" "$s" > "$g"
    fi
done

echo "threads,seed,round,setup_ms,scan_ms,merge_ms,contract_ms,edges_added,components_in,components_out" > "$OUT"

for t in 1 10; do
    for s in "${SEEDS[@]}"; do
        g="$GRAPH_DIR/g_${N}_s${s}.txt"
        "$PROF" "$t" "$s" < "$g" | tail -n +2 >> "$OUT"
    done
done

echo "wrote $OUT" >&2
